services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edu
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - "${WEB_PORT:-3000}:3000"

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    environment:
      BACKEND_PORT: ${API_PORT:-3001}
      FRONTEND_URL: http://localhost:${WEB_DEV_PORT:-5173},http://localhost:${WEB_PORT:-3000}
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/edu?schema=public
      JWT_SECRET: ${JWT_SECRET:-dev-secret}
    ports:
      - "${API_PORT:-3001}:${API_PORT:-3001}"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db_data:
