export const REF = {
  USER: 'USER',
  APPLICATION: 'APPLICATION',
  CHAT: 'CHAT',
  MESSAGE: 'MESSAGE',
  POST: 'POST',
  QUESTION: 'QUESTION',
  REVIEW: 'REVIEW',
  ACHIEVEMENT: 'ACHIEVEMENT',
  RECOMMENDATION: 'RECOMMENDATION',
  PROGRESS_TRACKER: 'PROGRESS_TRACKER',
  EVENT: 'EVENT',
} as const;
